### ISSUE TITLE
Unified build setup

### ISSUE THREAD

**Issue by bennycode** [welovecoding/welovecoding#10]
At the moment there is a `backend/package.json` and a `frontend/package.json` but to Heroku we deploy everything at once (backend + frontend). Thus it would be nice to have a central configuration point from where you can fire up the development backend and frontend. 

@TN1ck, do you have any ideas on how to do this? I could image a npm script starting two webpack instances or a Gulp system just for the purpose of managing two webpack instances. The goal is to have one start command which starts our dev environment (backend + frontend) and reloads the backend and/or frontend on changes during development (watcher task).

**Comment by TN1ck** [comment]
@bennyn 
I think it's the best thing to have them separate, I'll write something to make it work with Heroku. The general idea is, to serve the static assets of the frontend via the backend. I'll write a simple script that builds the frontend / backend and copies them somewhere and start the backend.

I cat actually do that now. :D :)

I can also write a simple command to starts the frontend / backend.

**Comment by bennycode** [comment]
Sounds good but this would still require that you have to run `npm install` in both (the frontend & backend) locations?

**Comment by TN1ck** [comment]
I created a `build.sh` script which builds the production release. When developing you currently need to `npm install` in both folders and `npm start` in both. We could also create a `start.sh` which does exactly that.

The deployment is working now btw!

**Comment by bennycode** [comment]
That sounds okay but can it handle this use case?

I want to run a single command which starts the development environment of the WLC backend and WLC frontend. When I then change something on the backend code I want to have these changes immediately reflected (autoreload or sth. similar). Same should apply to the frontend code. If I make changes to the frontend code I want to be able to see these changes on my localhost (served by the WLC development server) asap. This would enable us to develop backend code and frontend code simultaneously. @lipis made it possible to deliver this development experience for [gae-init](https://github.com/gae-init/gae-init/) and I believe that we can build in the same convenience into our application. 😃 

We can also consider splitting the backend code and frontend code into two different repositories. The frontend code could be linked into the backend code's repository by making use of [Git submodules](https://github.com/blog/2104-working-with-submodules). The goal at the end should still be having one command to start both of them but I thought it might be good to have them both in the same repository as we are sharing a lot of development dependencies (like `cross-env`, `ts-loader`, `tslint`, `tslint-loader`, `typescript` & `webpack`).

@TN1ck Should we add your `build.sh` script to the Travis CI [deployment goal](https://docs.travis-ci.com/user/deployment) or to Heroku's [Procfile](https://devcenter.heroku.com/articles/procfile)?

**Comment by TN1ck** [comment]
@bennyn The build.sh is currently executed by `npm preinstall`, for heroku nothing needs to be done - haven't checked Travis yet, should be similiar, maybe it's already working :D.

Yeah this is possible, the frontend/backend currently automatically apply changes. I don't know if it's actually wanted to have a browser reload when the backend changes, but I can add an option for that (you are losing the FE state with a browser reload). The command to start it all is a one-liner, can add that later.

The projects share some dependencies, but I think it would be too much hassle to combine them both with a single package.json. There are a lot of benefits with the current setup, let's start using it and fix problems as they arise.

**Comment by bennycode** [comment]
> The build.sh is currently executed by npm preinstall, for heroku nothing needs to be done - haven't checked Travis yet, should be similiar, maybe it's already working :D.

Because the `build.sh` script is platform specific I cannot run our project anymore. When executing `npm install`, the `npm preinstall` script is triggered and fails on my Windows machine, so we have to move the `build.sh` script to a place (like `.travis.yml`) which only affects unix systems.

**Screenshot:**

![screenshot](https://cloud.githubusercontent.com/assets/469989/26064998/e3d3a2d2-3992-11e7-9a41-7ff7c36e30f3.png)

> Yeah this is possible, the frontend/backend currently automatically apply changes. I don't know if it's actually wanted to have a browser reload when the backend changes, but I can add an option for that (you are losing the FE state with a browser reload). The command to start it all is a one-liner, can add that later.

No need to do that. I just want to reload the browser if frontend changes are made but I would like to guarantee that you can also make changes to the backend code at the same time, so that you can work on backend and frontend simultaneously (with having backend code reloaded when backend changes are made and frontend code reloaded when frontend changes are made).

> The projects share some dependencies, but I think it would be too much hassle to combine them both with a single package.json. There are a lot of benefits with the current setup, let's start using it and fix problems as they arise.

On second thought I agree on this one. As the project scales (and it will scale 🤗) it is very likely that we will progress on the backend and the frontend at a different pace. It also might be that we even deploy both projects to different places (backend code to Heroku, static scripts & styles to a CDN), so it's good to have them separated.

**Comment by TN1ck** [comment]
Aaaah ok, did not think about windows. What is the best option for simple scripts? I could write them in node.

**Comment by bennycode** [comment]
npm scripts would be ideal! 🌞 

Node's file system module can handle a bunch of things and if `mv` is required, then [fs-exta](https://github.com/jprichardson/node-fs-extra) is a good fit. The `fs-extra` package can also be used as a drop in replacement for `fs`, which is quite cool. 😎
