### ISSUE TITLE
TypeError: Cannot read property 'addSchema' of undefined

### ISSUE THREAD

**Issue by bennycode** [welovecoding/welovecoding#19]
I executed:

```bash
curl --data "username=tom&password=mypassword" https://welovecoding.herokuapp.com/login
```

Our server responded with:
> hey, find by username
> TypeError: Cannot read property 'addSchema' of undefined
> at Function.Model.getTableName (/app/backend/node_modules/sequelize/lib/model.js:1084:29)

I thought that I need to populate the database with some users executing `cd backend && npm run database:populate` but I received (`Unhandled rejection SequelizeBaseError: SQLITE_ERROR: no such table: Category`):

> POULATING USERS
hey, find by username
hey, find by username
hey, find by username
POPULATING CATEGORIES
POPULATING AUTHORS
POPULATING VIDEOS
Executing (default): SELECT `id`, `email`, `username`, `hash`, `salt`, `activationKey`, `resetPasswordKey`, `verified`,
 `createdAt`, `updatedAt` FROM `User` AS `User` WHERE `User`.`username` = 'benny' LIMIT 1;
Executing (default): SELECT `id`, `email`, `username`, `hash`, `salt`, `activationKey`, `resetPasswordKey`, `verified`,
 `createdAt`, `updatedAt` FROM `User` AS `User` WHERE `User`.`username` = 'roland' LIMIT 1;
Executing (default): SELECT `id`, `username`, `channelUrl`, `name`, `website`, `createdAt`, `updatedAt` FROM `Author` A
S `Author`;
Executing (default): SELECT `id`, `username`, `channelUrl`, `name`, `website`, `createdAt`, `updatedAt` FROM `Author` A
S `Author`;
Executing (default): SELECT `id`, `username`, `channelUrl`, `name`, `website`, `createdAt`, `updatedAt` FROM `Author` A
S `Author`;
Executing (default): SELECT `id`, `username`, `channelUrl`, `name`, `website`, `createdAt`, `updatedAt` FROM `Author` A
S `Author`;
Executing (default): INSERT INTO `Category` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (NULL,'java','2017-06-04 17:44
:24.427 +00:00','2017-06-04 17:44:24.427 +00:00');
Executing (default): INSERT INTO `Category` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (NULL,'python','2017-06-04 17:
44:24.427 +00:00','2017-06-04 17:44:24.427 +00:00');
Executing (default): INSERT INTO `Category` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (NULL,'elm','2017-06-04 17:44:
24.427 +00:00','2017-06-04 17:44:24.427 +00:00');
Executing (default): INSERT INTO `Author` (`id`,`username`,`channelUrl`,`createdAt`,`updatedAt`) VALUES (NULL,'gronkh',
'https://youtube.com/u/gronkh','2017-06-04 17:44:24.428 +00:00','2017-06-04 17:44:24.428 +00:00');
Executing (default): INSERT INTO `Author` (`id`,`username`,`channelUrl`,`createdAt`,`updatedAt`) VALUES (NULL,'coolyout
ubeguy','https://youtube.com/u/coolyoutubeguy','2017-06-04 17:44:24.428 +00:00','2017-06-04 17:44:24.428 +00:00');
Executing (default): INSERT INTO `Author` (`id`,`username`,`channelUrl`,`createdAt`,`updatedAt`) VALUES (NULL,'thecompu
terchannel','https://youtube.com/u/thecomputerchannel','2017-06-04 17:44:24.428 +00:00','2017-06-04 17:44:24.428 +00:00
');
Executing (default): INSERT INTO `Video` (`id`,`name`,`slug`,`createdAt`,`updatedAt`) VALUES (NULL,'Java Tutorial 1','J
ava Tutorial 1','2017-06-04 17:44:24.429 +00:00','2017-06-04 17:44:24.429 +00:00');
Executing (default): INSERT INTO `Video` (`id`,`name`,`slug`,`createdAt`,`updatedAt`) VALUES (NULL,'Turing Machine','Tu
ring Machine','2017-06-04 17:44:24.429 +00:00','2017-06-04 17:44:24.429 +00:00');
Executing (default): INSERT INTO `Video` (`id`,`name`,`slug`,`createdAt`,`updatedAt`) VALUES (NULL,'Lambda Calculus','L
ambda Calculus','2017-06-04 17:44:24.429 +00:00','2017-06-04 17:44:24.429 +00:00');
Executing (default): INSERT INTO `Video` (`id`,`name`,`slug`,`createdAt`,`updatedAt`) VALUES (NULL,'Badass Math','Badas
s Math','2017-06-04 17:44:24.429 +00:00','2017-06-04 17:44:24.429 +00:00');
Executing (default): SELECT `id`, `email`, `username`, `hash`, `salt`, `activationKey`, `resetPasswordKey`, `verified`,
 `createdAt`, `updatedAt` FROM `User` AS `User` WHERE `User`.`username` = 'tom' LIMIT 1;
Unhandled rejection SequelizeBaseError: SQLITE_ERROR: no such table: Category
    at Query.formatError (D:\dev\projects\welovecoding\welovecoding\backend\node_modules\sequelize\lib\dialects\sqlite\
query.js:348:14)

**Comment by TN1ck** [comment]
@bennyn I need to make some docs. You first need to execute `npm run database:reset` to create the tables, afterwards you can execute `npm run database:populate`. I will also remove all those console logs soon :sweat_smile:
