### ISSUE TITLE
Coding Standards & Linting Rules

### ISSUE THREAD

**Issue by bennycode** [welovecoding/welovecoding#20]
We need to establish a common set of rules for writing code. Some things to consider:
- https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
- https://github.com/feross/standard
- https://github.com/Flet/semistandard
- Tooling: https://github.com/prettier/prettier/releases/tag/1.4.0

**Comment by TN1ck** [comment]
With the new linting a lot of these things are kind of 'there', I have to check in what ways these rules apply though currently. Maybe we should extend the Readme with a 'Coding guidelines' section.

**Comment by bennycode** [comment]
Done with: https://github.com/welovecoding/welovecoding/blob/master/tslint.json
